baseURL = "https://bilbostack.com/"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
[params]
    hashtag = "#Bilbostack26"
    sponsorsDossierLink = "/docs/Bilbostack26-sponsors.es.pdf"
    sponsorsVisible = true
    agendaVisible = false
    ticketsOpen = true
    ticketsLink = "https://bilbostack2026.eventbrite.es"
    youtubeEmbedURL = "https://www.youtube.com/embed/cibqKWMiMQA?si=Edt43LCo1IW_Geue"
    contactEmail = "info@bilbostack.com"
    org = [
        { name = "Vicenç García-Altés", url = "https://x.com/vgaltes", image = "img/org/vicenç.jpg" },
        { name = "Ibon Landa", url = "https://x.com/ibonilm", image = "img/org/ibon.jpg" },
        { name = "Asier Marqués", url = "https://bsky.app/profile/asiermarques.com", image = "img/org/asier.jpg" },
        { name = "Fran Mosteiro", url = "https://x.com/fran_mosteiro", image = "img/org/fran.jpg" },
    ] 
    links = [
        { title = "Telegram", url = "https://t.me/bilbostack", image = "img/icons/icon-telegram.svg" },
        { title = "Bluesky", url = "https://bsky.app/profile/bilbostack.com", image = "img/icons/icon-bluesky.svg" },
        { title = "X", url = "https://x.com/bilbostack", image = "img/icons/icon-x.svg" },
        { title = "Github", url = "https://github.com/bilbostack", image = "img/icons/icon-github.svg" },
    ]  
    editions = [
        { year = 2012, url = "https://web.archive.org/web/20120502190422/http://bilbostack.com/", tracks = 2, speakers = 10, attendees = 150, network = "10x", color='orange' },
        { year = 2013, url = "https://web.archive.org/web/20130110075437/http://bilbostack.com/", tracks = 2, speakers = 10, attendees = 150, network = "10x", color='blue' },
        { year = 2014, url = "https://web.archive.org/web/20140205142714/http://bilbostack.com/", tracks = 2, speakers = 10, attendees = 150, network = "10x", color='purple' },
        { year = 2015, url = "https://web.archive.org/web/20150109210526/http://bilbostack.com/", tracks = 2, speakers = 10, attendees = 150, network = "10x", color='orange' },
        { year = 2016, url = "https://web.archive.org/web/20160109081707/http://bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='blue' },
        { year = 2017, url = "https://web.archive.org/web/20170601095000/http://bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='violet' },
        { year = 2018, url = "https://web.archive.org/web/20180129112902/http://bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='orange' },
        { year = 2019, url = "https://2019.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='pink' },
        { year = 2020, url = "https://2020.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='aqua' },
        { year = 2022, url = "https://2022.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='red' },
        { year = 2023, url = "https://2023.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='dark-yellow' },
        { year = 2024, url = "https://2024.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='purple' },
        { year = 2025, url = "https://2025.bilbostack.com/", tracks = 2, speakers = 8, attendees = 150, network = "10x", color='cyan' },
        { year = 2026, url = "https://bilbostack.com/", current = true, color='purple' }
    ]
    [[params.sponsorBlocks]]
        display = true
        title = "sponsors_main"
        class = "sponsors-xxl"
        sponsors = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png" },
            { name = "Diputación de Bizkaia", url = "https://www.bizkaia.eus", image = "img/sponsors/bfa.png" }
        ]
    [[params.sponsorBlocks]]
        display = true
        title = "sponsors_platino"
        class = "sponsors-xl"
        sponsors = [
            { name = "WordPress", url = "https://wordpress.com/es/hosting/?utm_medium=referral&utm_source=BilboStack26&utm_campaign=organizerlink", image = "img/sponsors/WP.png"  },
            { name = "BBK", url = "https://www.bbk.eus/es/proyectos/bbk-bootcamp-2/", image = "img/sponsors/bbk.png"  },
        ]
    [[params.sponsorBlocks]]
        display = true
        title = "sponsors_oro"
        class = "sponsors-l"
        sponsors = [
            { name = "Manfred", url = "https://getmanfred.com", image = "img/sponsors/manfred.svg"  },
            { name = "Inetum", url = "https://inetum.com/es", image = "img/sponsors/RVB_INETUM_20CM.png"   },
        ]
    [[params.sponsorBlocks]]
        display = true
        title = "sponsors_plata"
        class = "sponsors-m"
        sponsors = [
            { name = "Habla Computing", url = "https://www.hablaapps.com", image = "img/sponsors/habla.svg"  },
            { name = "Technosylva", url = "https://www.technosylva.com/es", image = "img/sponsors/techno-logo-color-300.png"  },

        ]
    [[params.sponsorBlocks]]
        display = true
        title = "sponsors_bronce"
        class = "sponsors-s"
        sponsors = [
            { name = "SeQura", url = "https://sequra.recruitee.com/career-page-jobs?jobs-b16f6b3f%5Btab%5D=Tech", image = "img/sponsors/sequra.png"  },
        ]
    [[params.collaboratorsBlocks]]
        display = false
        title = "collaborators"
        collaborators = [
            { name = "Bilboko Udala", url = "https://www.bilbaoekintza.eus/", image = "img/sponsors/bilbao.png", height = "2em", width = "auto"  }
        ]
[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 1
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 2
    [languages.eu]
      disabled = false
      languageCode = 'eu'
      languageName = 'EU'
      weight = 3
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true
[security]
  enableInlineShortcodes = true