baseURL = "https://bilbostack.com"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
[params]
    hashtag = "#Bilbostack25"
    sponsorsLink = "/docs/Bilbostack25-sponsors.es.pdf"
    sellingTickets = false
    ticketsLink = "https://www.eventbrite.com"
    youtubeEmbedURL = "https://www.youtube.com/embed/cibqKWMiMQA?si=Edt43LCo1IW_Geue"
    contactEmail = "info@bilbostack.com"
    org = [
        { name = "Vicenç García-Altés", url = "https://x.com/vgaltes", image = "img/org/vicenç.jpg" },
        { name = "Ibon Landa", url = "https://x.com/ibonilm", image = "img/org/ibon.jpg" },
        { name = "Asier Marqués", url = "https://x.com/asiermarques", image = "img/org/asier.jpg" },
        { name = "Fran Mosteiro", url = "https://x.com/fran_mosteiro", image = "img/org/fran.jpg" },
    ]
    links = [
        { title = "Twitter X", url = "https://twitter.com/bilbostack" },
        { title = "Telegram", url = "https://t.me/bilbostack20" },
        { title = "Github", url = "https://github.com/bilbostack" },
    ]
    [[params.sponsorBlocks]]
        display = false
        title = "sponsors_main"
        sponsors = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png", height = "12em" }
        ]
    [[params.sponsorBlocks]]
        display = false
        title = "sponsors_oro"
        sponsors = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png", height = "7em" }
        ]
    [[params.sponsorBlocks]]
        display = false
        title = "sponsors_plata"
        sponsors = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png", height = "5em" }
        ]
    [[params.sponsorBlocks]]
        display = false
        title = "sponsors_bronce"
        sponsors = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png", height = "3em" }
        ]
    [[params.collaboratorsBlocks]]
        display = false
        title = "collaborators"
        collaborators = [
            { name = "Bilboko Udala", url = "https://www.bilbao.eus/BilbaoEkintza", image = "img/sponsors/bilbao.png", height = "2em" }
        ]
[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 2
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 1
    [languages.eu]
      disabled = false
      languageCode = 'eu'
      languageName = 'EU'
      weight = 0
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true