baseURL = "https://bilbostack.com"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
[params]
    hashtag = "#Bilbostack25"
    sponsorsLink = "https://docs.google.com/presentation/d/10Brg_D1M-7E-SyBWArMMgeSF6AuzdXIgJyDGk7sklsk/edit?usp=sharing"
    youtubeEmbedURL = "https://www.youtube.com/embed/cibqKWMiMQA?si=Edt43LCo1IW_Geue"
    contactEmail = "info@bilbostack.com"
    org = [
        { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png" },
        { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png" },
        { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png" },
        { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png" },
    ]
    links = [
        { title = "Twitter X", url = "https://twitter.com/bilbostack" },
        { title = "Telegram", url = "https://t.me/bilbostack20" },
        { title = "Github", url = "https://github.com/bilbostack" },
    ]
    [[params.sponsorBlocks]]
        title = "sponsors_main"
        sponsors = [
            { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png", height = "12em" }
        ]
    [[params.sponsorBlocks]]
        title = "sponsors_oro"
        sponsors = [
            { name = "Vicenç García-Altés", url = "https://twitter.com/vgaltes", image = "img/org/vicenc.png", height = "5em" }
        ]
[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 2
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 1
    [languages.eu]
      disabled = false
      languageCode = 'eu'
      languageName = 'EU'
      weight = 0
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true